### ISSUE TITLE
Getting -1 day error (minus one day). 

### ISSUE THREAD

**Issue by 2urn** [agschwender/jquery.formatDateTime#5]
Hello,

For some reason with this input (only date no time):
 
    <span class="formatdatetime" data-datetime="2013-11-10" data-dateformat="d MM yy"></span> – <span class="formatdatetime" data-datetime="2014-09-26" data-dateformat="d MM yy"></span>

I am getting this result in my own time zone: 
**9** November 2013 – **25** September 2014

But folks in other time zones see it as it should be. Not sure why it's changing. 

This is on a WordPress site. My server settings are correct.

Any suggestions much appreciated!
Dimitry

**Comment by sp4ce** [comment]
What is your timezone ?

**Comment by agschwender** [comment]
It's just passing it to the JavaScript Date object. So here's what you're seeing according to my JavaScript console:

```
> new Date('2013-11-10')
> Sat Nov 09 2013 19:00:00 GMT-0500 (EST)
```

As you can see it's reporting the "wrong" date for negative timezones, because it's assuming the date is in UTC instead of the local timezone. You won't notice the error when the timezone is positive. I'd recommend that you specify the time component of the DateTime and I believe most browsers will assume that it's in the local timezone, e.g. 

```
> new Date('2013-11-10 00:00:00')
> Sun Nov 10 2013 00:00:00 GMT-0500 (EST)
```

**Comment by 2urn** [comment]
Ah, yes my time zone is -5 GMT EST. But I am generating the date from a ui calendar picker so there is no time value stored in data-datetime so I don't know how—would I append / concatenate it afterward?

**Comment by 2urn** [comment]
Mmm actually only works on some browsers. On others I now get:
NaN undefined NaN instead of formatted mumbers. How do I fix this?

**Comment by agschwender** [comment]
I can't really help you without seeing how you're doing the append/assignment and then also knowing which browsers you're getting the error.

**Comment by 2urn** [comment]
Ok. It's not working on iOS browser or on my css code editors built-in preview browser (Espresso for Mac). But works fine on Safari, Chrome on Mac.

Here is the snippet of code showing how I appended the time value:
https://gist.github.com/c6416b477f7cddfec288

**Comment by agschwender** [comment]
And when you inspect the data-datetime value in those browsers the value is correct?

**Comment by agschwender** [comment]
Actually, this will be helpful:

http://stackoverflow.com/questions/5324178/javascript-date-parsing-on-iphone

Looks like iPhone doesn't support that date format

**Comment by 2urn** [comment]
Yes the value is correct outside formatDateTime. Ah, so I have to write a script to do this operation before entering the date in data-datetime?

    var arr = "2010-03-15 10:30:00".split(/[- :]/),
    date = new Date(arr[0], arr[1]-1, arr[2], arr[3], arr[4], arr[5]);

console.log(date);
//-> Mon Mar 15 2010 10:30:00 GMT+0000 (GMT Standard Time)

**Comment by agschwender** [comment]
Or you need to know the client's timezone and adjust accordingly. Or a fix needs to be put into the plugin to use UTC to format when the `data-datetime` value is a date string rather than a datetime string.

**Comment by 2urn** [comment]
I don't know how to do that—so I  think I am stuck.

**Comment by agschwender** [comment]
Added a setting for `utc` in version `1.1.6`. Since the browser is assuming the date is in UTC when no time is specified, the date must be rendered in UTC to see it as you're expecting it. What that would mean for you is, when rending bare dates, you should set the settings as `{utc: true}` in addition to whatever other settings you want to use.

I haven't seen your code, but I'm guessing you have something onload like

```javascript
document.ready(function() { 
    $('.formatdatetime').formatDateTime();
});
```

What you'd want to do is for dates (not datetimes), is something like this:

```javascript
document.ready(function() {
    $('.formatdate').formatDateTime(undefined, {utc: true});
});
```

**Comment by 2urn** [comment]
Wow! Thank you so much. I was just loading the script with no settings (it is a wordpress site using handle bar templates for cpts. But I can add js to the templates I am using so I will do what you suggest and implement the new setting you created for UTC. This is so in keeping with you whole concept to make formatting Date and time simple and easy. Will let you know how it goes. 

Much appreciated!

**Comment by 2urn** [comment]
Ok. I uploaded the new 1.1.5 version and changed my code to:

```
<h5>{{#exhibition_details_opening-date}}<span class="formatdate" data-datetime="{{{exhibition_details_opening-date}}}" data-dateformat="d MM yy"></span>{{/exhibition_details_opening-date}}{{#exhibition_details_closing-date}} – <span class="formatdate" data-datetime="{{{exhibition_details_closing-date}}}" data-dateformat="d MM yy"></span>{{/exhibition_details_closing-date}}</h5>

<h5>{{#exhibition_details_reception}}<b>Reception:</b> <span class="formatdate" data-datetime="{{{exhibition_details_reception}}}" data-dateformat="DD d MM yy"></span>   {{/exhibition_details_reception}} {{#exhibition_details_reception-time}} · {{exhibition_details_reception-time}}{{/exhibition_details_reception-time}}</h5>
```

And added this to my footer:
    (function($){
    $('.formatdate').formatDateTime(undefined, {utc: true});
    })(jQuery);

Result: all the dates are -1 and every date is the same as the first date variable (9 November which is back to -1 error) in the document.

**Comment by agschwender** [comment]
You want version `1.1.6`.

**Comment by 2urn** [comment]
I downloaded  1.1.6 but it still says:

    /*
 * jQuery Format Date/Time - v1.1.5 - 2015-03-08
 * https://github.com/agschwender/jquery.formatDateTime
 * Copyright (c) 2015 Adam Gschwender
 * Licensed MIT, GPLv2
*/

**Comment by agschwender** [comment]
Sorry, forgot to bump the version number in those files, but yeah that's the correct version based on the date. If you want to download it again, the version number has been corrected but functionality-wise it shouldn't matter.

**Comment by 2urn** [comment]
Ok, I must be using it wrong then. Can you please give me an example for the new syntax using date only in a span?

**Comment by agschwender** [comment]
If that link you provided:

[redacted]

is up-to-date, that version is _not_ the new one.

**Comment by 2urn** [comment]
Ah ok. I will update again.

**Comment by 2urn** [comment]
Ok, Adam I replaced with the latest version. Still experiencing same results, though—I must have the syntax wrong.

**Comment by agschwender** [comment]
If that link you provided is up-to-date, it's still the old version. Not sure what you're updating it with or where you're downloading it from, but it should look like this:

https://github.com/agschwender/jquery.formatDateTime/blob/1.1.6/dist/jquery.formatDateTime.js

If you can't find "utc" in the file, you're using an old version.

**Comment by 2urn** [comment]
AH! I found the problem—one of my developers had also wrapped version 1.0 in a plugin and so site was loading both—overriding the latest version. Fixed and now works perfectly! Thank you so much, Adam!

**Comment by 2urn** [comment]
[can you please remove link to my dev site?] Thanks.

**Comment by agschwender** [comment]
Done
